dev_pro_frontend:
    resource: "@DevProFrontendBundle/Controller/"
    type:     annotation
    prefix:   /

dev_pro_backend:
    resource: "@DevProBackendBundle/Controller/"
    type:     annotation
    prefix:   /

 # app/config/routing.yml
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

hwi_oauth_redirect:
    resource: "@HWIOAuthBundle/Resources/config/routing/redirect.xml"
    prefix:   /connect

hwi_oauth_login:
    resource: "@HWIOAuthBundle/Resources/config/routing/login.xml"
    prefix:   /login
