# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    app.mailer:
        class:        DevPro\BackendBundle\Newsletter\NewsletterManager
        arguments: ['@mailer', '@templating']
    app.notification:
              class: DevPro\BackendBundle\Controller\LayoutController
              arguments:
                      entityManager: "@doctrine.orm.entity_manager"
